-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.complaints
(
    complaint_id integer NOT NULL,
    resident_id integer NOT NULL,
    category_id integer NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    submission_date date NOT NULL,
    CONSTRAINT complaints_pkey PRIMARY KEY (complaint_id)
);

CREATE TABLE IF NOT EXISTS public.residents
(
    resident_id integer NOT NULL,
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    ward integer NOT NULL,
    email character varying(100) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT residents_pkey PRIMARY KEY (resident_id),
    CONSTRAINT residents_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.service_categories
(
    category_id integer NOT NULL,
    category_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT service_categories_pkey PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS public.status_logs
(
    log_id integer NOT NULL,
    complaint_id integer NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status_date date NOT NULL,
    CONSTRAINT status_logs_pkey PRIMARY KEY (log_id)
);

ALTER TABLE IF EXISTS public.complaints
    ADD CONSTRAINT complaints_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.service_categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.complaints
    ADD CONSTRAINT complaints_resident_id_fkey FOREIGN KEY (resident_id)
    REFERENCES public.residents (resident_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.status_logs
    ADD CONSTRAINT status_logs_complaint_id_fkey FOREIGN KEY (complaint_id)
    REFERENCES public.complaints (complaint_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;